### PR TITLE
Drop Sessions Table and Delete `lib/tasks/sessions.rake`

### LINKED ISSUE #723: Fix `rake sessions:cleanup`
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
- `4.0.2+portage-4.0.3`

**Expected behaviour:**
- `rake sessions:cleanup` should be executable
**Actual behaviour:**
```
aaron@ubuntu:~/Documents/GitHub/roadmap
$ rake sessions:cleanup --trace
** Invoke sessions:cleanup (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute sessions:cleanup
rake aborted!
NameError: uninitialized constant ActiveRecord::SessionStore
Did you mean?  SessionsController
/home/aaron/Documents/GitHub/roadmap/lib/tasks/sessions.rake:8:in `block (2 levels) in <top (required)>'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/task.rb:281:in `block in execute'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/task.rb:281:in `each'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/task.rb:281:in `execute'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/task.rb:199:in `synchronize'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/task.rb:188:in `invoke'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/application.rb:182:in `invoke_task'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/application.rb:138:in `each'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/application.rb:138:in `block in top_level'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/application.rb:147:in `run_with_threads'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/application.rb:132:in `top_level'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/application.rb:83:in `block in run'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/lib/rake/application.rb:80:in `run'
/usr/share/rvm/gems/ruby-2.7.6@dmp/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/usr/share/rvm/gems/ruby-2.7.6@dmp/bin/rake:23:in `load'
/usr/share/rvm/gems/ruby-2.7.6@dmp/bin/rake:23:in `<main>'
/usr/share/rvm/gems/ruby-2.7.6@dmp/bin/ruby_executable_hooks:22:in `eval'
/usr/share/rvm/gems/ruby-2.7.6@dmp/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => sessions:cleanup
```

### PR DESCRIPTION
**Pull request by aaronskiba**
Fixes #723

Changes proposed in this PR:
- Drop `sessions` table from the app's db
  - Within [`config/initializers/session_store.rb`](https://github.com/portagenetwork/roadmap/blob/deployment-portage/config/initializers/session_store.rb), the app has been configured to use `cookie_store` for quite some time now. The sessions table has not been used since this change has occurred.
- Delete `lib/tasks/sessions.rake`
  - This file's rake task was created to clear the sessions table / prevent it from becoming overpopulated. However, because the sessions table is no longer used, this rake task is no longer needed. In addition, this rake task is currently broken: https://app.rollbar.com/a/ualbertalib/fix/item/dmp_assistant/490
-  To go along with these codebase changes, the cronjob for `rake sessions:cleanup` can be removed from all environments (production, staging, and sandbox).

### CODE REVIEW

**Comment by aaronskiba** [comment]
The failing MySQL actions are expected behaviour after running the PR within this migration.

**Comment by aaronskiba** [comment]
This PR’s migration is meant to simply drop the `sessions` table:
```ruby
class DropSessionsTable < ActiveRecord::Migration[6.1]
  def up
    drop_table :sessions
  end
```
Unfortunately, it is really transforming the `db/schema.rb` file: https://github.com/portagenetwork/roadmap/pull/859/commits/124bc52c4bd32d5f72bb8480f6ab8073d836bede#diff-cbf8b25d6d853acf58fa9057841f407d29ffe90649c75cf9e3f51b2d6e3aa1d3
Which in turn is breaking the MySQL workflows. Multiple errors like the following are thrown:
```
ActiveRecord::MismatchedForeignKey: Column `org_id` on table `annotations` does not match column `id` on `orgs`, which has type `bigint unsigned`. To resolve this issue, change the type of the `org_id` column on `annotations` to be :bigint. (For example `t.bigint :org_id`).
18
Original message: Mysql2::Error: Referencing column 'org_id' and referenced column 'id' in foreign key constraint 'fk_rails_aca7521f72' are incompatible.
```
This error is occurring because the primary keys are being changed from type `:integer` to type `:serial`. The primary key type was never specified in some of these older migrations and a Rails upgrade must be responsible for the change in the default type. However, unlike the primary key, the foreign key was in fact specified as type integer.

There must be a difference in how MySQL vs PostgreSQL interpret the serial type. The `primary_key :serial <-> foreign_key :integer` works with PostgreSQL, but breaks with MySQL.

The `db/schema.rb` file is auto-generated and not meant to be physically altered. I had tested out migrations in the past and always encountered this same behaviour. I reached out to the upstream developers. One of them admitted that they had always been physically altering the file to keep the MySQL workflows working.

We discussed it a bit and it sounds like all of the various upstream developers are okay with ditching the MySQL workflows; I guess everyone is using PostgreSQL. The Rails 7 upgrade also currently includes some migrations that would also result in the MySQL workflows breaking.

**Review by lagoan — DISMISSED** [review]
Good job Aaron. I like the way you made the sessions migration reversible.

**Review by lagoan — APPROVED** [review]
LGTM!

**Pull request merged**
