### PR TITLE
only show managed orgs in statistics filter

### LINKED ISSUE #94: Fix usage statistics Org count
Fixing issue #93 shows that all changes in a plan's funder create a new organization. This will add noise to the current way we are fetching statistics as we do not filter the count:

https://github.com/portagenetwork/roadmap/blob/8ab5afc91f49dbd6a1baeb39bd4be0e6e5632935/app/controllers/usage_controller.rb#L80-L82

We should look at how current listings for organizations ignore these created funders and follow the same way of doing it for presenting statistics.

### PR DESCRIPTION
**Pull request by pengyin-shan**
Fixes #94 .

Changes proposed in this PR:
- Only managed orgs are shown in the filter

### CODE REVIEW

**Comment by lagoan** [comment]
Take a look also to the `usage_controller`

https://github.com/portagenetwork/roadmap/blob/8ab5afc91f49dbd6a1baeb39bd4be0e6e5632935/app/controllers/usage_controller.rb#L80-L82

The results should also be addressed there.

And while we are fixing these issues you could look for all the instances of Org.all and see if it makes sense to change scope it is being used.

**Comment by pengyin-shan** [comment]
> Take a look also to the `usage_controller`
> 
> https://github.com/portagenetwork/roadmap/blob/8ab5afc91f49dbd6a1baeb39bd4be0e6e5632935/app/controllers/usage_controller.rb#L80-L82
> 
> The results should also be addressed there.
> 
> And while we are fixing these issues you could look for all the instances of Org.all and see if it makes sense to change scope it is being used.

to confirm, we want the total count show all orgs including the random orgs created by funder right? It will be categorized as the 'other organizations'

**Comment by lagoan** [comment]
I think we want to show the organizations that are managed, or at least those that are created by super administrators. We do not want the organizations or funders created from user input for plan or account creation.

**Comment by pengyin-shan** [comment]
> I think we want to show the organizations that are managed, or at least those that are created by super administrators. We do not want the organizations or funders created from user input for plan or account creation.

Got it. I'll exclude unmanaged organizations from all statistics then

**Comment by pengyin-shan** [comment]
As a record, the current org status in the user statistics page is :
1. 'Download Global Statistics' triggers for *all orgs* since this function is open to super admin
2. 'No. users joined during last year' & 'No. plans during last year' & 'No. plans by template' keep default setting *No Change needed*
3. `No. plans created based off your templates` might related to another issue. But for this ticket, *No Change needed*
4. `Run your own filter` section is set up display *only managed orgs*

**Review by lagoan — APPROVED** [review]
LGTM

**Pull request merged**
